### ISSUE TITLE
How to show/hide with animation?

### ISSUE THREAD

**Issue by klaszlo8207** [MustansirZia/overlay_container#4]
I need Transform scale (0-1 when show and 1-0 when hide, with duration) and animationcontroller but I can not achive this, can you help me?

**Comment by MustansirZia** [comment]
Hi @klaszlo8207.
I can surely try. What you could do I guess is to show the Overlay always and pass a `true` value to the `show` property. Now, once that's visible you can use the Transformed widget as the `child` of the `OverlayContainer`. This will keep the Overlay always visible but will scale the contents inside it. 

What I mean is this:
```dart
OverlayContainer(
   show: true,
   child: AnimatedBuilder(
       animation: _scaleAnimation,
       builder: (context, child) {
           return Transform.scale(
               scale: _scaleAnimation.value,
               child: child,
            );
        },
        child: Container(height: 50, width: 50, color: Colors.red), // This will scale.
   ),
)
```

Hope it helps!

**Comment by klaszlo8207** [comment]
Tnx
