### ISSUE TITLE
Made a CompositedTransformTarget-based derivitive

### ISSUE THREAD

**Issue by micimize** [MustansirZia/overlay_container#6]
Just thought I'd mentioned that I made a [derivative widget](https://gist.github.com/micimize/7579a66861cf56ba241b224a64566d51) based on yours to solve some problems I was having (https://github.com/flutter/flutter/issues/19445#issuecomment-570105928)

Notably I call `_overlayEntry.markNeedsBuild();` instead of rebuilding the widget when it's already expanded.

Might put together an actual PR later also

**Comment by MustansirZia** [comment]
@micimize Hey!
Very interesting indeed. I do like the fact about using `.markNeedsBuild()`. It seems the right way to go. 
May I know, however, what is the use case here for using a `CompositedTransformTarget` instead of a well, plain `Container`?

**Comment by micimize** [comment]
The `CompositedTransformFollower` follows the position of the `CompositedTransformTarget`, meaning the overlay follows the inline/inline-block widget position on scroll.

Not necessarily universally desirable, but was important for my use case

**Comment by hermitdave** [comment]
@micimize can you please tell me how to use your version ? I need an overlay to scroll with parent

managed to get it working - was missing offset and material in root of the overlay

**Comment by micimize** [comment]
@hermitdave here you go https://dartpad.dev/61505c392f877bd0b2df9103d5a2bb97 
I'd also try out the [translation approach](https://github.com/flutter/flutter/issues/19445#issuecomment-577236173), which is probably more performant, but seems like something the flutter team might consider a "bug" in the future

**Comment by hermitdave** [comment]
@micimize thanks I used the original gist and got it working. When overlay is visible, it prevents the underlying scrollviewer from accepting any scroll events. Did you have the same issue ? if so is there any workaround ?

**Comment by micimize** [comment]
@hermitdave lets continue usage/troubleshooting convo in the [gist](https://gist.github.com/micimize/61505c392f877bd0b2df9103d5a2bb97)

I'm gonna go ahead and close this as it wasn't even a real issue to begin with, but I left some [notes](https://gist.github.com/micimize/7579a66861cf56ba241b224a64566d51#gistcomment-3289253) on the gist
